# Theme kazemnejad/jekyll-course-website-template
# Github Ref: https://github.com/kazemnejad/jekyll-course-website-template
# Live Ref: https://kazemnejad.github.io/jekyll-course-website-template/

# Site settings
course_name: "Code@TACC:Connected"
course_description: "Connected is an innovative and exciting virtual summer program that lets students explore where coding meets communities.The Code@TACC: Connected STEM Camp provides an opportunity for students to fully experience the scientific process from sensor design to analyzing and presenting results-based narratives visually. The two-week virtual camp begins with environmental sensor construction while correlating them to human senses using the Raspberry Pi platform. The sensors are then taken into the field to collect in situ sample data. The data includes atmospheric, auditory, surface, and radiance derived sources from multiple biomes. The collected data is then analyzed by the students both computationally within JupyterNotebook’s written in Python, and aesthetically through physical representations. Scientific hypotheses are then formed through which the results are presented in a fair-like atmosphere. The format of the final presentations use physical dioramas combined with data-driven visual simulations emitting from student-made electronic designs. In short, the camp compresses an undergrad-level research experience in ecology/geoscience/environmental science, computer science, electrical engineering, and creative design into a 10-day enrichment program. The result of the hackathon-like atmosphere generates a sense of ownership of the projects within the participants which leads to intimate knowledge gain based on both wide and deep understanding through research."
course_semester: "Summer 2023"

# Git Pages Settings
baseurl: "/connected/" # the subpath of your site, e.g. /blog/
url: "https://code-at-tacc.github.io/" # the base hostname & protocol for your site

# Local Settings
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

schoolname: "Texas Advanced Computing Center Education and Outreach Group"
schoolurl: "https://www.tacc.utexas.edu/education/k-12-outreach"
twitter_username: TACC

address: |
    Texas Advanced Computing Center
    J.J. Pickle Research Campus, Building 205 (ACB)
    10100 Burnet Rd
    Austin, TX 78758

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ["_images", "_css"]
exclude: ["develop"]

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

defaults:
    - scope:
          path: ""
          type: "assignments"
      values:
          layout: "assignment"
